-- 완료된 중고거래의 총 금액이 70만원 이상인 ID, 닉네임, 총거래금액
-- 총거래금액 기준 ASC

SELECT 
    G.USER_ID,
    G.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS G
    LEFT JOIN USED_GOODS_BOARD AS B ON G.USER_ID = B.WRITER_ID
WHERE
    B.STATUS = 'DONE'
GROUP BY
    G.USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES;
